name: Terraform
on:
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 0.12.16
      TF_ACTION_WORKING_DIR: .
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.GITHUB_ADMIN_SSH_PRIVATE_KEY }}
      - name: Cat known_hosts and git clone
        run: |
          cd /tmp
          cat ~/.ssh/known_hosts
          git clone git@github.com:alexbde/terraform-demo
          ls -a terraform-demo
          ls -a terraform-demo/modules/include-me
          rm -rf terraform-demo
      - name: Terraform initialize
        uses: hashicorp/terraform-github-actions@v0.6.3
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.TF_ACTION_WORKING_DIR }}
          tf_actions_comment: true
